### 모든 대여 기록 조회
GET http://localhost:8080/admin/rentals

### 대여 기록 생성
POST http://localhost:8080/admin/rentals
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2,
  "reservationId": 1
}

### 대여 반납 처리
PATCH http://localhost:8080/admin/rentals/1/return