### 모든 예약 조회
GET http://localhost:8080/admin/reservations

### 예약 상태 변경
PATCH http://localhost:8080/admin/reservations/1/status
Content-Type: application/json

{
  "status": "CONFIRMED"
}

### 예약 취소
PATCH http://localhost:8080/admin/reservations/1/status
Content-Type: application/json

{
  "status": "CANCELLED"
}